TRUE_COMPANIES = {
    "KSH International Limited",
    "KSH International Private Limited",
    "Bhandary Metal Extrusion Private Limited",
    "Bajaj Finance Limited",
    "Beck India Limited",
    "CARE Ratings Limited",
    "Cindus Corporation",
    "Nidec Industrial Automation India Private Limited",
    "Emirates Transformer & Switchgear Limited",
    "Georgia Transformer Corporation",
    "HDFC Bank Limited",
    "Hindalco Industries Limited",
    "IndusInd Bank Limited",
    "KSH Distriparks Private Limited",
    "KSH Infra Park IV Private Limited",
    "KSH Infra Park VI Private Limited",
    "KSH Integrated Logistics Private Limited",
    "KSH Project Management Services Private Limited",
    "Kanj & Co. LLP",
    "Kirtane & Pandit LLP",
    "MUFG Intime India Private Limited",
    "Malabar India Fund Limited",
    "National Payments Corporation of India",
    "National Securities Depository Limited",
    "Nuvama Wealth Management Limited",
    "Parijat Foundation",
    "Precision Wires India Limited",
    "Reserve Bank of India",
    "Savli Copper Products Private Limited",
    "Shubhkamal Leasing and Investment Private Limited",
    "Solar Energy Corporation of India Limited",
    "State Bank of India",
    "Virginia Transformer Corporation",
    "Waterloo Motors Private Limited",
    "Vedanta Limited",
}
