TRUE_PERSONS = {
    # Original verified names
    "Sarthak Malvadkar",
    "Kushal Subbayya Hegde",
    "Pushpa Kushal Hegde",
    "Rajesh Kushal Hegde",
    "Rohit Kushal Hegde",
    "Sandesh Bhagwat",
    "Amod Joshi",
    "Karunakar N. Bhandary",
    "Narayna B. Shetty",
    "Jayaram N. Shetty",
    "Ajay Shriram Patil",
    "Shanti Gopalkrishnan",
    "Sangeeta Ramprasad Rai",
    "Rupal K. Sancheti",
    "Salil Ajay Bhargava",
    "Ajay Menon",
    "Sunil Nagayya Shetty",
    "Kumar Tiwari",
    "Indu Jacob",

    # Additional people verified from document context
    "Eric Bacha",
    "Sachin Gawade",
    "Pravin Teli",
    "Siddharth Jadhav",
    "Tushar Gavankar",
    "Kishan Rastogi",
    "Abhijit Diwan",
    "Karunakar Hegde",
    "Kushal Hegde",
    "Pushpa Hegde",
    "Rajesh Hegde",
    "Rohit Hegde",
    "Vijay Hegde",
    "Maithili Rajesh Hegde",
}
